<?php

namespace FondOfSpryker\Shared\CheckoutPage;

interface CheckoutPageConstants
{
    public const SHOW_REGION_FOR_CONTRIES = 'SHOW_REGION_FOR_CONTRIES';
    public const CHECKOUT_PAGE_FIRST_NAME_VALIDATION_MIN_LENGTH_COUNT = 'CHECKOUT_PAGE_FIRST_NAME_VALIDATION_MIN_LENGTH_COUNT';
    public const CHECKOUT_PAGE_LAST_NAME_VALIDATION_MIN_LENGTH_COUNT = 'CHECKOUT_PAGE_LAST_NAME_VALIDATION_MIN_LENGTH_COUNT';
    public const CHECKOUT_PAGE_DEFAULT_VALIDATION_MIN_LENGTH_COUNT = 'CHECKOUT_PAGE_DEFAULT_VALIDATION_MIN_LENGTH_COUNT';
    public const CHECKOUT_PAGE_PRIORITY_COUNTRIES_COM_STORE = 'CHECKOUT_PAGE_PRIORITY_COUNTRIES_COM_STORE';
}
