<?php

namespace FondOfSpryker\Yves\CheckoutPage\Process\Steps;

use Spryker\Shared\Kernel\Transfer\AbstractTransfer;
use SprykerShop\Yves\CheckoutPage\Process\Steps\PaymentStep as SprykerPaymentStep;
use Symfony\Component\HttpFoundation\Request;

class PaymentStep extends SprykerPaymentStep
{
    /**
     * if customer got a 100% voucher the payment step is not needed
     *
     * @param \Spryker\Shared\Kernel\Transfer\AbstractTransfer $quoteTransfer
     * @return bool
     */
    public function requireInput(AbstractTransfer $quoteTransfer): bool
    {

        return ($quoteTransfer->getTotals()->getSubtotal() < $quoteTransfer->getTotals()->getDiscountTotal())
            ? true
            : false;
    }

    public function execute(Request $request, AbstractTransfer $quoteTransfer)
    {
        if ($this->requireInput() === false) {
            return $this->setZeroPayment($request, $quoteTransfer);
        } else {
            return parent::execute($request, $quoteTransfer); // TODO: Change the autogenerated stub
        }
    }

    protected function setZeroPayment(Request $request, AbstractTransfer $quoteTransfer): AbstractTransfer
    {
        $paymentHandler = $this->paymentPlugins->get(prepaymentPrepayment);
        $paymentHandler->addToDataClass($request, $quoteTransfer);

        return $this->calculationClient->recalculate($quoteTransfer);
    }
}
